# Generated by Django 4.1.2 on 2022-10-10 17:34

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_cust", models.CharField(max_length=100)),
                ("email_rest", models.EmailField(max_length=254)),
                (
                    "phone_cust",
                    models.CharField(
                        max_length=20,
                        validators=[api.models.Customer_fields_validators.phone_number],
                    ),
                ),
                ("address_cust", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Customer_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description_cust_ord", models.CharField(max_length=500)),
                ("status_cust_ord", models.IntegerField(default=1)),
                (
                    "customer_cust_ord",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_prod", models.CharField(max_length=100)),
                ("description_prod", models.CharField(max_length=500)),
                ("price_prod", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity_prod", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Order_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "order_ord_prod",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customer_order",
                    ),
                ),
                (
                    "product_ord_prod",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
        ),
    ]
