# Generated by Django 4.1.2 on 2022-10-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="email_rest",
            new_name="email_cust",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="price",
            new_name="price_ord_prod",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="quantity",
            new_name="quantity_ord_prod",
        ),
    ]
