# Generated by Django 4.1.2 on 2022-10-10 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_email_rest_customer_email_cust_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_item",
            old_name="order_ord_prod",
            new_name="order_ord_item",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="price_ord_prod",
            new_name="price_ord_item",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="product_ord_prod",
            new_name="product_ord_item",
        ),
        migrations.RenameField(
            model_name="order_item",
            old_name="quantity_ord_prod",
            new_name="quantity_ord_item",
        ),
    ]
