# Generated by Django 4.1.2 on 2022-10-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_order_ord_prod_order_item_order_ord_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_prod",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
