# Generated by Django 4.1.2 on 2022-10-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_price_prod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_item",
            name="price_ord_item",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
